[features]
seeds = false
[programs.devnet]
sol_anchor_contract = "GkPTy4QjES2JJMYVR2C7EkhRbjjTa9d9YLZoXu9RJDEK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
