[features]
seeds = false
[programs.localnet]
sol_anchor_contract = "4Nnb1v32be4zUXwBBrugiDsK3Pgs8uTmEcdk3UbrQxwJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/simrat12/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
