[features]
seeds = false
[programs.mainnet]
sol_anchor_contract = "CvhsZhKCwMDjB7z77ixon6NU4fzEViu2TnvMvwoEY82V"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/Solana_Stablecoin/new_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

